<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Country;
use App\Models\Agency;
use App\Models\Mr;
use App\Models\Patient;
use App\Models\MedicalReport;
use App\Models\XrayReport;
use App\Models\AgencyInvoice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Seed Admin User
        $admin = User::create([
            'name' => 'Admin',
            'email' => 'admin@example.com',
            'username' => 'admin',
            'password' => Hash::make('admin123'),
            'role' => 'Admin',
            'status' => '1',
            'mobile_no' => '+880 1756-441699',
            'user_folder' => 'admin',
            'file_permission' => 'all',
            'company_name_en' => 'Best Health Diagnostic & Medical Center',
            'company_address_en' => '1/A DIT Extension Road, Fakirapool, Dhaka-1000',
            'company_phone_en' => '+880 1756441699',
            'company_pax_en' => '100',
            'company_name_bn' => 'বেস্ট হেলথ ডায়াগনস্টিক ও মেডিকেল সেন্টার',
            'company_address_bn' => '১/এ ডিআইটি এক্সটেনশন রোড, ফকিরাপুল, ঢাকা-১০০০',
            'company_phone_bn' => '+৮৮০ ১৭৫৬-৪৪১৬৯৯',
            'company_pax_bn' => '১০০',
        ]);

        // Seed another user
        User::create([
            'name' => 'Nabiul Hasan',
            'email' => 'nabiul@example.com',
            'username' => 'nabiul',
            'password' => Hash::make('nabiul123'),
            'role' => 'MR',
            'status' => '1',
            'mobile_no' => '+880 1756-441699',
            'user_folder' => 'nabiul',
            'file_permission' => 'receive',
        ]);

        // 2. Seed Countries with specific IDs
        $countriesList = [
            1 => "JORDAN",
            2 => "BANGLADESH",
            33 => "U.A.E",
            5 => "SINGAPORE",
            6 => "BAHRAIN",
            7 => "CANADA",
            8 => "INDIA",
            9 => "IRAQ",
            10 => "ITALY",
            11 => "JAPAN",
            12 => "KOREA",
            13 => "KUWAIT",
            14 => "LEBANON",
            15 => "MALAYSIA",
            16 => "MALDIVES",
            17 => "MEXICO",
            18 => "NEPAL",
            19 => "OMAN",
            20 => "PAKISTAN",
            21 => "POLAND",
            22 => "LIBYA",
            23 => "QATAR",
            24 => "MISHOR",
            25 => "U.S.A",
            26 => "BRUNEI",
            27 => "K.S.A",
            28 => "CONGO",
            34 => "GREECE",
            31 => "MAURITIUS",
            32 => "THAILAND",
            35 => "HONG KONG",
            36 => "LONDON",
            37 => "AUSTRALIA",
            38 => "CYPRUS",
            39 => "SPAIN",
            40 => "TANZANIA",
            41 => "TAIWAN",
            42 => "REPUBLIC OF CHAD",
            53 => "BRASIL",
            44 => "SRILANKA",
            45 => "BELARUS",
            46 => "DENMARK",
            47 => "SOUTH SUDAN",
            48 => "WEST INDIES",
            49 => "SOUTH KOREA",
            50 => "SICILY",
            51 => "VIETNAM",
            52 => "SAIPAN",
            55 => "PORTUGAL",
            56 => "NEW ZEALAND",
            57 => "TAJIKISTAN",
            58 => "ALGERIA",
            59 => "GARMANY",
            61 => "EAST TIMOR",
            62 => "PADMA SETU",
            63 => "SWITZERLALD",
            64 => "CROACIA",
            65 => "PELARUSH",
            66 => "NORWAY",
            67 => "JORJIA",
            68 => "EUROPE",
            69 => "K S A",
            70 => "AZERBAIJAN",
            71 => "SUDAN",
            72 => "BRUNEAI",
            73 => "SYPRISE",
            74 => "COMBODIA",
            75 => "IRELAND",
            76 => "NETHERLAND",
            77 => "TIMOR LESTE",
            78 => "RUSSIA",
            79 => "SAUDIA ARABIAN",
            80 => "MAURITIUS",
            81 => "CHINA",
            82 => "UKRAINE",
            83 => "SHYPRAS",
            84 => "PALAU",
            85 => "DUBAI",
            86 => "FIJI",
            87 => "FRANCE",
            88 => "AUSTRIA",
            89 => "ROMANIA",
            90 => "UZBEKISTAN",
            91 => "AZERBAIJAN",
            92 => "SYPRISE",
            93 => "TAJIKISTAN",
            94 => "UZBEKISTAN",
            95 => "HUNGARY",
            96 => "KYRGYZSTAN",
            97 => "SERBIA",
            98 => "TURKEY",
            99 => "MOUNTAIN",
            100 => "PHILIPPINES",
            101 => "ARMENIA",
            102 => "LAOS",
            103 => "MONGOLIA",
            104 => "ALBANIA",
            105 => "CROATIA",
            106 => "EGYPT",
            107 => "REPUBLIC OF CYPRUS",
            108 => "MOLDOVA",
            109 => "BOSNIA",
            110 => "BULGARIA",
            111 => "KOSOVO",
            112 => "SEYCHELLES",
            113 => "GREECECYPRUS"
        ];
        
        $countries = [];
        foreach ($countriesList as $id => $cName) {
            if (isset($countries[$cName])) {
                continue; // Skip duplicate country names to satisfy unique index
            }
            $countries[$cName] = Country::create(['id' => $id, 'name' => $cName]);
        }

        // 3. Seed Agencies
        $agenciesList = [
            1 => ["name" => "SELF", "price" => 1000],
            2 => ["name" => "M/S SOHA OVERSEAS", "price" => 500],
            3 => ["name" => "RIDOY INTR;", "price" => 0],
            4 => ["name" => "TAQWAH OVERSAES", "price" => 0],
            5 => ["name" => "RAIHAN VAI", "price" => 0],
            6 => ["name" => "MINHAZ OVERSEAS", "price" => 0],
            7 => ["name" => "TAZ TOURS", "price" => 0],
            8 => ["name" => "NM Tours & Travels", "price" => 0],
            9 => ["name" => "Saiful vai", "price" => 0],
            10 => ["name" => "Jamadar Razib", "price" => 0],
            11 => ["name" => "Sakil", "price" => 0],
            12 => ["name" => "Sonia Apa", "price" => 0],
            13 => ["name" => "QK Quick Express LTD", "price" => 0],
            14 => ["name" => "Holy Tread", "price" => 0],
            15 => ["name" => "Toushi International", "price" => 0],
            16 => ["name" => "Bismillah Traders", "price" => 0],
            17 => ["name" => "Taqwah Oversees", "price" => 0],
            18 => ["name" => "Jeinpuri Oversees", "price" => 0],
            19 => ["name" => "Faruk vai", "price" => 0],
            20 => ["name" => "Al-Mobarok", "price" => 0],
            21 => ["name" => "Smart Care", "price" => 0],
            22 => ["name" => "Ranger Oversees", "price" => 0],
            23 => ["name" => "Sumon vai Singapore", "price" => 0],
            24 => ["name" => "MERIGOLD", "price" => 0],
            25 => ["name" => "TALENT OVERSAES", "price" => 0],
            26 => ["name" => "COSBA OVERSAES", "price" => 0],
            27 => ["name" => "UCKSEL LTD", "price" => 0],
            28 => ["name" => "AL JAHANGIR", "price" => 0],
            29 => ["name" => "MIM INTEARNATIONAL", "price" => 0],
            30 => ["name" => "MODINA AIR", "price" => 0],
            31 => ["name" => "PROMINENT MARIN ACADEMY", "price" => 0],
            32 => ["name" => "ALI MUNSHIGANJ", "price" => 530],
            33 => ["name" => "MOTIN INTERPRACE", "price" => 0],
            34 => ["name" => "DALU VAI", "price" => 530],
            35 => ["name" => "RASHEL VAI", "price" => 0],
            36 => ["name" => "RAHAN VAI", "price" => 530],
            37 => ["name" => "MONIR ALLWAY", "price" => 530],
            38 => ["name" => "MOFIZ IQBAL", "price" => 530],
            39 => ["name" => "RAIHAN VAI CHAKRY", "price" => 530],
            40 => ["name" => "MONIR ROWMARY", "price" => 530],
            41 => ["name" => "KHALED SYLLHET", "price" => 500],
            42 => ["name" => "ANOWAR AIR", "price" => 530],
            43 => ["name" => "SAMSUZZAMAN", "price" => 530],
            44 => ["name" => "NUSAIBA OVERSAES", "price" => 0],
            45 => ["name" => "TAZ TOURS(SAMAD)", "price" => 0],
            46 => ["name" => "S.ZAMAN", "price" => 500],
            47 => ["name" => "SASCO INT:", "price" => 650],
            48 => ["name" => "IBRAHIM KHALIL CHAPAI", "price" => 500],
            49 => ["name" => "STS", "price" => 500],
            50 => ["name" => "M.ENTERPRISE", "price" => 500],
            51 => ["name" => "ANIK WELDING", "price" => 550],
            52 => ["name" => "KHALED SYLLHET(SHELU)", "price" => 0],
            53 => ["name" => "TAZ TOURS (MAMUN)", "price" => 0],
            54 => ["name" => "rasel vai", "price" => 600],
            55 => ["name" => "MONIR VAI ALLWAY", "price" => 500],
            56 => ["name" => "NIZAM OVER SEAS", "price" => 500],
            57 => ["name" => "TAJNIN OVERSAES", "price" => 0],
            58 => ["name" => "FEITH AIR", "price" => 0],
            59 => ["name" => "AL SHAMIM OVERSAES", "price" => 0],
            60 => ["name" => "LB GROOP", "price" => 0],
            61 => ["name" => "TAZ TOURS (MURAD)", "price" => 0],
            62 => ["name" => "LITON AIR INTERNATIONAL", "price" => 0],
            63 => ["name" => "JAMADAR JAHID VAI", "price" => 0],
            64 => ["name" => "AL-BORAT", "price" => 500],
            65 => ["name" => "PABNA OVERSEAS", "price" => 500],
            66 => ["name" => "NORSINGDI(ALAMIN)", "price" => 500],
            67 => ["name" => "COX.S BAZAR OVERSAES", "price" => 0],
            68 => ["name" => "UKSEL", "price" => 500],
            69 => ["name" => "KAMAL INTETNATIONAL", "price" => 0],
            70 => ["name" => "TARIQUL VAI", "price" => 500],
            71 => ["name" => "KALAM NOWGA SHELU", "price" => 500],
            72 => ["name" => "SHEBLU VAI", "price" => 500],
            73 => ["name" => "NAZMUL CHI", "price" => 500],
            74 => ["name" => "SR.TRAVELS", "price" => 500],
            75 => ["name" => "MAHIMA OVERSAES", "price" => 0],
            76 => ["name" => "ADIB AIR", "price" => 0],
            77 => ["name" => "ALI.MUNSHIGANJ", "price" => 500],
            78 => ["name" => "AL-MUSAFIR", "price" => 0],
            79 => ["name" => "TAZ GOFFAR VAI", "price" => 0],
            80 => ["name" => "SONIA N.SINGDI", "price" => 500],
            81 => ["name" => "FARHAN OVERSEAS", "price" => 500],
            82 => ["name" => "FOYEZ SONARGA SHELU", "price" => 500],
            83 => ["name" => "AL-MADINA SHALMAN", "price" => 0],
            84 => ["name" => "SB INTERNATIONAL", "price" => 500],
            85 => ["name" => "kustiya ovaersaes", "price" => 0],
            86 => ["name" => "AL SHAFI INTERNATIONAL", "price" => 0],
            87 => ["name" => "KUSTIA OVERSEAS(SHELU)", "price" => 500],
            88 => ["name" => "JM.ENT:", "price" => 500],
            89 => ["name" => "jm.ent:SHELU", "price" => 0],
            90 => ["name" => "THE SIRAJ VAI S", "price" => 0],
            91 => ["name" => "SHARMIN M", "price" => 0],
            92 => ["name" => "sharmin m /s", "price" => 0],
            93 => ["name" => "JAKIR VAI /SHELU", "price" => 500],
            94 => ["name" => "BULBUL VAI RANGPUR/SHELU", "price" => 500],
            95 => ["name" => "SALAM TRADING", "price" => 600],
            96 => ["name" => "AL-FARUK TRAVELS/SHELU", "price" => 500],
            97 => ["name" => "IDMC/SHELU", "price" => 500],
            98 => ["name" => "SOHIDUL IDMC /SHELU", "price" => 0],
            99 => ["name" => "SOHIDUL IDMC /SHELU", "price" => 0],
            100 => ["name" => "MIT INT", "price" => 0],
            101 => ["name" => "NAHID HASAN ISLAM T SHELU", "price" => 500],
            102 => ["name" => "KAMAL MOHIN/SHELU", "price" => 500],
            103 => ["name" => "BINIMOY TRAVELS", "price" => 0],
            104 => ["name" => "VEANA OVERSEAS", "price" => 0],
            105 => ["name" => "MZ INT:/SHELU", "price" => 0],
            106 => ["name" => "H.N.GANJ/SHELU", "price" => 500],
            107 => ["name" => "JA.AVIATION", "price" => 0],
            108 => ["name" => "JR.AVIATION", "price" => 0],
            109 => ["name" => "MEHEDI VAI", "price" => 600],
            110 => ["name" => "MEHEDI VAI/SHELU", "price" => 0],
            111 => ["name" => "OVERSEAS TRADING (PVT) LTD. SOHEL RANA", "price" => 0],
            112 => ["name" => "AFNAN OVERSEAS", "price" => 0],
            113 => ["name" => "JAMADAR TANBIR VAI", "price" => 0],
            114 => ["name" => "JEWEL VAI", "price" => 600],
            115 => ["name" => "JAKIR VAI /SHELU", "price" => 500],
            116 => ["name" => "ECONOMIC TRAVELS SERVICE", "price" => 0],
            117 => ["name" => "MAHIRA SOKAL INT:/SHELU", "price" => 0],
            118 => ["name" => "VIRTUAL WORLD VISION/RUBEL", "price" => 0],
            119 => ["name" => "GENERAL TRAINING CENTER", "price" => 600],
            120 => ["name" => "UNION OVERSEAS", "price" => 0],
            121 => ["name" => "EASIWAY INTERNATIOAL( MURAD)", "price" => 0],
            122 => ["name" => "easiway internatioal( MAMUN)", "price" => 0],
            123 => ["name" => "EASYWAY INTERNATIONAL(GOFFAR)", "price" => 0],
            124 => ["name" => "EMTIAJ VAI/SHELU", "price" => 0],
            125 => ["name" => "VERSATILE OVERSEAS LTD:/SHELU", "price" => 0],
            126 => ["name" => "RM CORPROTION", "price" => 0],
            127 => ["name" => "BEJOY DADA/SHELU", "price" => 500],
            128 => ["name" => "ABU SALE VAI / SHELU", "price" => 500],
            129 => ["name" => "TAREK VAI ROWMARY/SHELU", "price" => 0],
            130 => ["name" => "DEPEN BISWAS/SHELU", "price" => 500],
            131 => ["name" => "NAYEM VAI / SHELU", "price" => 0],
            132 => ["name" => "BINIMOY TRAVELS", "price" => 0],
            133 => ["name" => "JM ENT : SHELU", "price" => 0],
            134 => ["name" => "DOBIR VA GANGCHIL /SHELU", "price" => 0],
            135 => ["name" => "RUBEL AIR", "price" => 0],
            136 => ["name" => "MOZAHID VAI/SHELU", "price" => 600],
            137 => ["name" => "mozahid vai/RUBEL", "price" => 0],
            138 => ["name" => "riyaz vai /rubel", "price" => 0],
            139 => ["name" => "AL-MUNSUR OVERSEAS /SHELU", "price" => 0],
            140 => ["name" => "SADDAM VAI", "price" => 0],
            141 => ["name" => "SHEIKH AIR INTERNATIONAL/SHELU", "price" => 0],
            142 => ["name" => "JASHIM /SHELU", "price" => 0],
            143 => ["name" => "MASUD RANA /SHELU", "price" => 0],
            144 => ["name" => "KAMAL INTERNATIONAL /RUBEL", "price" => 0],
            145 => ["name" => "UPDATE OVERSASE/RUBEL", "price" => 0],
            146 => ["name" => "SAFE LIFE INTER//RUBEL", "price" => 0],
            147 => ["name" => "SIDDIK VAI /SHELU", "price" => 0],
            148 => ["name" => "AL KAMIS NASIR VAI/RUBEL", "price" => 0],
            149 => ["name" => "ROHANI TRAVELS /SHELU", "price" => 0],
            150 => ["name" => "ALIF AIR /SHELU", "price" => 0],
            151 => ["name" => "AZ ZAHARA INTER/RUBEL", "price" => 0],
            152 => ["name" => "KAMAL INTETNATIONAL/SHELU", "price" => 0],
            153 => ["name" => "JAPAN AIR DALIM VAI /SHELU", "price" => 0],
            154 => ["name" => "MANIK SINGAPORE /SHELU", "price" => 0],
            155 => ["name" => "BILALL VAI / SHELU", "price" => 0],
            156 => ["name" => "brahmanbaria export", "price" => 0],
            157 => ["name" => "MAMUN SYELAT /SHELU", "price" => 0],
            158 => ["name" => "BULBUL VAI PABNA/SHELU", "price" => 0],
            159 => ["name" => "MONIR KAKA /SHELU", "price" => 0],
            160 => ["name" => "AL-MAMUN /HALIMA", "price" => 0],
            161 => ["name" => "YOUSUF VAI /SHELU", "price" => 0],
            162 => ["name" => "RIVER SKY OVERSEAS LTD./SHELU", "price" => 0],
            163 => ["name" => "JAMADDAR AZAD VAI", "price" => 0],
            164 => ["name" => "SHIKDER TRAVELS /SHELU", "price" => 0],
            165 => ["name" => "WORLD WIDE / SUMID/SHELU", "price" => 0],
            166 => ["name" => "jahangir vai /rubel", "price" => 0],
            167 => ["name" => "AL-AMIN N .SINGDI /SHELU", "price" => 0],
            168 => ["name" => "JAMADAR PALASH", "price" => 0],
            169 => ["name" => "AKASH VAI", "price" => 0],
            170 => ["name" => "WELL TEC/ROBIN/RUBEL", "price" => 0],
            171 => ["name" => "BIPLOV VAI. STS/SHELU", "price" => 0],
            172 => ["name" => "TAZUL SYALHET / SHELU", "price" => 0],
            173 => ["name" => "M AZIZ AND SONS", "price" => 0],
            174 => ["name" => "ENGINEER/JASHIM/SHELU", "price" => 0],
            175 => ["name" => "KAMAL PARVEZ (JHARNA)", "price" => 0],
            176 => ["name" => "RAZU KUSTIA/SHELU", "price" => 0],
            177 => ["name" => "BACHU VAI SHELU", "price" => 0],
            178 => ["name" => "TAIZUL VAI (SHELU)", "price" => 0],
            179 => ["name" => "TAZUL VAI (SHELU)", "price" => 0],
            180 => ["name" => "MARUF VAI/SHELU", "price" => 0],
            181 => ["name" => "AFTAB VAI/SHELU", "price" => 0],
            182 => ["name" => "HABIB VAI HALIMA", "price" => 0],
            183 => ["name" => "WASIS OVERSEAS/SHELU", "price" => 0],
            184 => ["name" => "ALAMGIR MALAYSIA /SHELU", "price" => 0],
            185 => ["name" => "JAMADAR SHAHADAD/RUBEL", "price" => 0],
            186 => ["name" => "JAMADAR AZAD/RUBEL", "price" => 0],
            187 => ["name" => "SR SUMON AKON ENTER PRAIS /HALIMA", "price" => 500],
            188 => ["name" => "NOMAN TRAVELS /SHELU", "price" => 0],
            189 => ["name" => "MONIR VOLA /SHELU", "price" => 0],
            190 => ["name" => "HAFIZA APA N.GANG/SHELU", "price" => 0],
            191 => ["name" => "JOJ VAI /SHELU", "price" => 0],
            192 => ["name" => "MAURITIUS/ ATIK TRAVELS /SHELU", "price" => 0],
            193 => ["name" => "ASIANLING ENTERPRISE/ SHELU", "price" => 0],
            194 => ["name" => "square late zietex apparels /shelu", "price" => 0],
            195 => ["name" => "scarlet jitex apparels", "price" => 0],
            196 => ["name" => "AHSAN HABIB SAUTHKOREA/SHELU", "price" => 0],
            197 => ["name" => "SAGOR MARMA/SHELU", "price" => 0],
            198 => ["name" => "Rokeya Mansion/Rezaul Anchel", "price" => 0],
            199 => ["name" => "AL GRAND", "price" => 500],
            200 => ["name" => "PREMIUM OVERSASE/RUBEL", "price" => 500],
            201 => ["name" => "FARUK U.A.E./SHELU", "price" => 0],
            202 => ["name" => "NORAIL TRAVELS", "price" => 0],
            203 => ["name" => "BCB TRAVELS", "price" => 0],
            204 => ["name" => "BCB TRAVELS /SHELU", "price" => 0],
            205 => ["name" => "VIRTUAL WORLD VISION", "price" => 0],
            206 => ["name" => "scarlet jitex apparelsFORHAD MALAYSIA", "price" => 0],
            207 => ["name" => "FORHAD MALAYSIA", "price" => 0],
            208 => ["name" => "MAGURA OVERSEAS/BEST", "price" => 0],
            209 => ["name" => "UGNITED OVERSEAS", "price" => 0],
            210 => ["name" => "Sonartory Trade International", "price" => 0],
            211 => ["name" => "UGNITED OVERSEAS/RUBEL", "price" => 0],
            212 => ["name" => "Parul International RL-2493", "price" => 0],
            213 => ["name" => "ORKO OVERSASE/HALIMA", "price" => 0],
            214 => ["name" => "AL EKRA/HALIMA", "price" => 0],
            215 => ["name" => "HABIB VAI", "price" => 0],
            216 => ["name" => "Rezaul Enterprise", "price" => 0],
            217 => ["name" => "PRANTIK TRAVELS/RASEL/SHELU", "price" => 0],
            218 => ["name" => "ROKY ANCHEL/SHELU", "price" => 0],
            219 => ["name" => "SABBIR OVERSEAS", "price" => 0],
            220 => ["name" => "MUNNA VAI //SHELU", "price" => 0],
            221 => ["name" => "FARUK TRAVEL &TUROSE/RUBEL", "price" => 0],
            222 => ["name" => "MOZAMMEL VAL/ SHELU", "price" => 600],
            223 => ["name" => "ABDUL HADI", "price" => 600],
            224 => ["name" => "ARAFAT ANCHEL /SHELU", "price" => 0],
            225 => ["name" => "ARAFAT ANCHEL /SHELU", "price" => 0],
            226 => ["name" => "MUJAHID VAI/RUBEL", "price" => 0],
            227 => ["name" => "SHAHIN VAI /SHELU", "price" => 0],
            228 => ["name" => "ANONNO OPURBO", "price" => 0],
            229 => ["name" => "SHILA OVERSEAS /SHELU", "price" => 0],
            230 => ["name" => "KARIM VAI/shelu", "price" => 0],
            231 => ["name" => "SOBUJ /K /SHELU", "price" => 0],
            232 => ["name" => "SHEMU ROYAL", "price" => 0],
            233 => ["name" => "reza vai jarnalist /shelu", "price" => 0],
            234 => ["name" => "MOHOR VAI /SHELU", "price" => 0],
            235 => ["name" => "ADNAN VAI /SHELU", "price" => 0],
            236 => ["name" => "REZA VAI /SHELU", "price" => 0],
            237 => ["name" => "RAZU VAI ROWMARY TRAVELS", "price" => 0],
            238 => ["name" => "Mother Care Travels", "price" => 0],
            239 => ["name" => "MOTALEB VAI 2/S", "price" => 0],
            240 => ["name" => "MINI TOURS AND RIDOY VAI /RUBEL", "price" => 0],
            241 => ["name" => "LUK BUSINESS (MITHU) SHELU", "price" => 0],
            242 => ["name" => "HAIDORY TRADE INTERNATIONAL", "price" => 0],
            243 => ["name" => "Khulna Tours and Travel", "price" => 0],
            244 => ["name" => "MONR VAI SONARGAON/SHELU", "price" => 0],
            245 => ["name" => "AL-MUSAFIR 222", "price" => 0],
            246 => ["name" => "NUR VAI UPDATE/RUBEL", "price" => 0],
            247 => ["name" => "MAHMUD VAI", "price" => 0],
            248 => ["name" => "GOLENOOR VAI", "price" => 0],
            249 => ["name" => "R.B.MAX TRAVELS & TOURS/ SHELU", "price" => 0],
            250 => ["name" => "ANOWARA APA/SHELU", "price" => 0],
            251 => ["name" => "GOLENOR VAI", "price" => 0],
            252 => ["name" => "IDEAL BUSINESS CENTRE", "price" => 0],
            253 => ["name" => "GOLENOR VAI/SHELU", "price" => 0],
            254 => ["name" => "HOSSAIN (KUWAIT)", "price" => 0],
            255 => ["name" => "AH INTERNATIONAL", "price" => 0],
            256 => ["name" => "AL-MAMUN VAI/SHELU", "price" => 0],
            257 => ["name" => "MI OVERSASAE/HALIMA", "price" => 0],
            258 => ["name" => "TAZMOHOL TRAVELS / SHELU", "price" => 0],
            259 => ["name" => "SATKHIRA ABIR", "price" => 0],
            260 => ["name" => "MONIR VAI /HALIMA", "price" => 0],
            261 => ["name" => "REDOY VAI/ HALIMA", "price" => 0],
            262 => ["name" => "ANIK WELDING TRECHNICAL TRAINING CENTER", "price" => 0],
            263 => ["name" => "SHAJAHAN VAI", "price" => 0],
            264 => ["name" => "TULI OVERSEAS", "price" => 0],
            265 => ["name" => "KASHBON", "price" => 0],
            266 => ["name" => "EUROPE STUDY ADVISORE", "price" => 0],
            267 => ["name" => "DIABARI EMPLOYMRNT/R", "price" => 0],
            268 => ["name" => "JOHIRUL ITALY", "price" => 0],
            269 => ["name" => "LAMYA GARMANSH", "price" => 0],
            270 => ["name" => "ISLAM VAI SINGAPURE", "price" => 0],
            271 => ["name" => "JAHANGIR VAI LONG /SHELIU", "price" => 0],
            272 => ["name" => "KHAN TRAVELS & TOURS", "price" => 0],
            273 => ["name" => "Basic Power And Care Overseas Ltd.", "price" => 0],
            274 => ["name" => "SAIFUL VAI MALY", "price" => 0],
            275 => ["name" => "AIR INTERNATIONAL", "price" => 1100],
            276 => ["name" => "SHUMI ENTERPRISE", "price" => 500],
            277 => ["name" => "HANIF VAI / KAMRUL", "price" => 0],
            278 => ["name" => "GIAS UDDIN VAI", "price" => 900],
            279 => ["name" => "KAMAL HOSSAIN", "price" => 1000],
            280 => ["name" => "MS. SHOVA", "price" => 500],
            281 => ["name" => "HANIF VAI", "price" => 600],
            282 => ["name" => "IGNITATE OVERSEAS(DIPOK VAI)", "price" => 600],
            283 => ["name" => "HARUN VAI", "price" => 0],
            284 => ["name" => "HIKMA INTERNATIONAL", "price" => 530],
            285 => ["name" => "SIRAJ VAI", "price" => 500],
            286 => ["name" => "LANKA BANGLA GNAT", "price" => 500],
            287 => ["name" => "MR. SUJON", "price" => 1000],
            288 => ["name" => "gurdian international", "price" => 0],
            289 => ["name" => "MAKKA MADINA TRAVELS", "price" => 0],
            290 => ["name" => "LEGAL WAY", "price" => 0],
            291 => ["name" => "DAWLAT EXPORT", "price" => 0],
            292 => ["name" => "BESCO", "price" => 0],
            293 => ["name" => "VIP OVERSEES", "price" => 0],
            294 => ["name" => "JAKIA TOURS & TRAVELS", "price" => 0],
            295 => ["name" => "M ELIAS", "price" => 0],
            296 => ["name" => "THREE SONS", "price" => 0],
            297 => ["name" => "DNATA", "price" => 0],
            298 => ["name" => "RAHMAN OVERSEAS", "price" => 0],
            299 => ["name" => "S ZISHAN OVERSEAS", "price" => 0],
            300 => ["name" => "AKHI", "price" => 0],
            301 => ["name" => "JOBA TRADES", "price" => 0],
            302 => ["name" => "TAJE INTERNATIONAL", "price" => 0],
            303 => ["name" => "MSK GLOBAL TOURS & TRAVELS", "price" => 0],
            304 => ["name" => "ABID TOURS & TRAVELS", "price" => 0],
            305 => ["name" => "BANGLE AIR SERVICER", "price" => 0],
            306 => ["name" => "FM TREADERS", "price" => 0],
            307 => ["name" => "RAJ BAHADUR TRAVELS", "price" => 0],
            308 => ["name" => "PAN SHIRI TOURS & TRAVELS", "price" => 0],
            309 => ["name" => "RUMA SAVAR", "price" => 0],
            310 => ["name" => "AMIR HAMZA AIR INTERNATIONAL", "price" => 0],
            311 => ["name" => "YEASIN TOURS & TRAVELS", "price" => 0],
            312 => ["name" => "MALEK BHAI", "price" => 0],
            313 => ["name" => "K1", "price" => 0],
            314 => ["name" => "PRANRAJ", "price" => 0],
            315 => ["name" => "MINA", "price" => 0],
            316 => ["name" => "AIRNET", "price" => 0],
            317 => ["name" => "GREEN MOUNT EXPORT LTD", "price" => 0],
            318 => ["name" => "POTUAKHALI TOURS & TRAVELS", "price" => 0],
            319 => ["name" => "RS OVERSEAS", "price" => 0],
            320 => ["name" => "ANOWER BHAI", "price" => 0],
            321 => ["name" => "ROMAN TRAVELS", "price" => 0],
            322 => ["name" => "ZISAN INTERNATIONAL", "price" => 0],
            323 => ["name" => "ZAMZAM HOLYDAY", "price" => 0],
            324 => ["name" => "BONGO AIR INTERNATIONAL", "price" => 0],
            325 => ["name" => "ALIZA EMPLOYMENT AGENCY", "price" => 0],
            326 => ["name" => "OMEGA OVERSEAS RL-1872", "price" => 0],
            327 => ["name" => "SHAWON", "price" => 0],
            328 => ["name" => "BGO TRAVELS", "price" => 0],
            329 => ["name" => "CAPITAL DHAKA TOUR &TRAVELS AGENCY", "price" => 0],
            330 => ["name" => "HAYAT TRAVELS HUB", "price" => 0],
            331 => ["name" => "NAHID", "price" => 0],
            332 => ["name" => "TITAN AVIATION", "price" => 0],
            333 => ["name" => "ANZ AIR SERVICE", "price" => 0],
            334 => ["name" => "MODEL AVITION", "price" => 0],
            335 => ["name" => "NEW KHAN AIR INTERNATIONAL", "price" => 0],
            336 => ["name" => "TAMIM TRAVELS", "price" => 0],
            337 => ["name" => "SMD INTERNATIONAL", "price" => 0],
            338 => ["name" => "MD HRIDOY", "price" => 0],
            339 => ["name" => "APON AIR", "price" => 0],
            340 => ["name" => "ANOWRA APA", "price" => 0],
            341 => ["name" => "anowra apa/duniya", "price" => 0],
            342 => ["name" => "SHELY", "price" => 0],
            343 => ["name" => "SIM TRADE", "price" => 0],
            344 => ["name" => "M/S RONY ENTERPRISE", "price" => 0],
            345 => ["name" => "konggais air international", "price" => 0],
            346 => ["name" => "SMT TRAINING & TESTING PRIVATE LIMITED", "price" => 0],
            347 => ["name" => "TRAVEL TREASURE", "price" => 0],
            348 => ["name" => "AREFIN VA /SHELU", "price" => 600],
            349 => ["name" => "VARTULE WORLD", "price" => 0],
            350 => ["name" => "Guardian International", "price" => 0],
            351 => ["name" => "ARIF BD", "price" => 0],
            352 => ["name" => "SUPREME CONSULTANCY", "price" => 0],
            353 => ["name" => "SUMAIYA", "price" => 0],
            354 => ["name" => "SK TOURS AND TRAVELS", "price" => 0],
            355 => ["name" => "TOPLINK", "price" => 0],
            356 => ["name" => "RUBEL SHEIKH", "price" => 0],
            357 => ["name" => "AMER BHAI TRAVELS", "price" => 0],
            358 => ["name" => "NIJHUM TOURS & TRAVELS", "price" => 0],
            359 => ["name" => "hadi", "price" => 0],
            360 => ["name" => "DIN ISLAM", "price" => 600],
            361 => ["name" => "ALL LINE TOURS&TRAVELS", "price" => 0],
            362 => ["name" => "M/S AZAN BUSINESS INTERNATIONAL", "price" => 500],
            363 => ["name" => "MOSTAFIZ", "price" => 0],
            364 => ["name" => "AYESHA TOURS AND TRAVELS", "price" => 0],
            365 => ["name" => "Roj aviation Enterprise", "price" => 0],
            366 => ["name" => "EXPLORE HORIZONS INTRENATIONAL CONSULTANCY", "price" => 0],
            367 => ["name" => "MARJUQ TRADE INTERNATIONAL", "price" => 0],
            368 => ["name" => "SOLEMAN", "price" => 0],
            369 => ["name" => "NISHAN OVERSEAS", "price" => 0],
            370 => ["name" => "MISSION OVERSEAS", "price" => 500],
            371 => ["name" => "PACIFIC", "price" => 0],
            372 => ["name" => "BARNALI", "price" => 0],
            373 => ["name" => "MEHMAN GLOBAL SERVICE SR", "price" => 800],
            374 => ["name" => "AL SAHARA", "price" => 0],
            375 => ["name" => "PRIME OVERSEAS", "price" => 1000],
            376 => ["name" => "A2 SS TOURS", "price" => 0],
            377 => ["name" => "MARHABA TOURS AND TRAVELS", "price" => 0],
            378 => ["name" => "MD SOFIULLAH", "price" => 700],
            379 => ["name" => "AFRA OVERSWAS", "price" => 0],
            380 => ["name" => "LARA TOUR AND TRAVELS", "price" => 0],
            381 => ["name" => "AYMAN TOURS AND TRAVELS", "price" => 0],
            382 => ["name" => "PATOWARY OVERSEAS", "price" => 0],
            383 => ["name" => "PROBASHI TOURS & TRAVELS", "price" => 0],
            384 => ["name" => "WONDER OVERSEAS", "price" => 0],
            385 => ["name" => "ALBUS COMPANY", "price" => 0],
            386 => ["name" => "FLY POINT (MASUD)", "price" => 1200],
            387 => ["name" => "ABHA OVERSEAS", "price" => 500],
            388 => ["name" => "ANIK OVERSEAS", "price" => 400],
            389 => ["name" => "ABF TRADE", "price" => 0],
            390 => ["name" => "SV", "price" => 500],
            391 => ["name" => "JUMEIRA AIR INT:", "price" => 0],
            392 => ["name" => "THE FENY OVERSEAS", "price" => 0],
            393 => ["name" => "AIR SMART INTERNATIONAL", "price" => 500],
            394 => ["name" => "GT TOURS & TRAVELS", "price" => 0],
            395 => ["name" => "SALAM AIR INT:", "price" => 0],
            396 => ["name" => "SHAWLIN OVERSEAS", "price" => 500],
            397 => ["name" => "RIMSA OVERSEAS", "price" => 0],
            398 => ["name" => "ALHAMDULILLAH ENTERPRISE", "price" => 500],
            399 => ["name" => "PADMA MANPOWER LIMITED", "price" => 0],
            400 => ["name" => "SELIM (SR)", "price" => 600],
            401 => ["name" => "BANIK AIR INTERNATIONAL", "price" => 500],
            402 => ["name" => "FS OVERSEAS", "price" => 500],
            403 => ["name" => "MONIR MAGURA", "price" => 0],
            404 => ["name" => "MK TRAVELS & TOURISM LTD.", "price" => 500],
            405 => ["name" => "JANNAT TOURS AND TRAVELS", "price" => 800],
            406 => ["name" => "Saimon International", "price" => 0],
            407 => ["name" => "A-ONE TRAVELS", "price" => 500],
            408 => ["name" => "MEPA OVERSEAS", "price" => 0],
            409 => ["name" => "HANIF UNCLE", "price" => 0],
            410 => ["name" => "FAMILY AIR INTERNATIOMAL", "price" => 500],
            411 => ["name" => "BELI TOURS&TRAVELS", "price" => 500],
            412 => ["name" => "SR INTERNATIONAL", "price" => 0],
            413 => ["name" => "SN INTERNATIONAL", "price" => 0],
            414 => ["name" => "YOUSUF OVERSEAS", "price" => 0],
            415 => ["name" => "MOAZZEM OVERSEAS", "price" => 0],
            416 => ["name" => "SPT INTERNATIONAL", "price" => 700],
            417 => ["name" => "DHAKA TRAVELS", "price" => 500],
            418 => ["name" => "SHOHAN OVERSEAS LTD.", "price" => 0],
            419 => ["name" => "AL BARES COMPANY", "price" => 0],
            420 => ["name" => "UNIQUE STAND BEST", "price" => 500],
            421 => ["name" => "MALAYSIA", "price" => 0],
            422 => ["name" => "ALAM OVERSEAS", "price" => 0],
            423 => ["name" => "LIZA APA", "price" => 500],
            424 => ["name" => "FAYSAL .K", "price" => 0],
            425 => ["name" => "SWEDEN", "price" => 0],
            426 => ["name" => "dhanshiry tours & travels", "price" => 0],
            427 => ["name" => "FALCON TRAVELS", "price" => 600],
            428 => ["name" => "ABDUL HAI (SR)", "price" => 600],
            429 => ["name" => "AL-AMIN KHONDOKER", "price" => 600],
            430 => ["name" => "HEMISPHERE TOUR OPERATOR", "price" => 0],
            431 => ["name" => "FAHIMA OVERSEAS", "price" => 800],
            432 => ["name" => "ZF OVERSEAS", "price" => 0],
            433 => ["name" => "MD GAUSUL AZAM", "price" => 0],
            434 => ["name" => "JAMAN TOURS AND TRAVELS", "price" => 0],
            435 => ["name" => "SI.SHIBLU", "price" => 0],
            436 => ["name" => "AL HADI TRAVELS & TOUSR", "price" => 0],
            437 => ["name" => "NS OVERSEAS", "price" => 0],
            438 => ["name" => "SHIMUN TRAVELS", "price" => 0],
            439 => ["name" => "MARIA D", "price" => 450],
            440 => ["name" => "BILASH TRAVELS AND TOURS", "price" => 600],
            441 => ["name" => "SEAGULL GROUP", "price" => 0],
            442 => ["name" => "JOURNALIST (SR)", "price" => 1000],
            443 => ["name" => "ALOKHIK LIMITED", "price" => 0],
            444 => ["name" => "MINGHUI INTERNATIONAL LIMITED,", "price" => 0],
            445 => ["name" => "BONDHON TRAVELS", "price" => 500],
            446 => ["name" => "SIKANDER MIA EASY GO", "price" => 800],
            447 => ["name" => "ASIA TRAVELS AND TOURS", "price" => 0],
            448 => ["name" => "SHAWPNO POOL TRAVELS", "price" => 1200],
            449 => ["name" => "RELIANCE TOURS & TRAVELS", "price" => 500],
            450 => ["name" => "AL HUMAYDI OVERSEAS", "price" => 500],
            451 => ["name" => "APON AIR INTERNATIONAL", "price" => 0],
            452 => ["name" => "MAHBUB INTERNATIONAL AGENCIES", "price" => 0],
            453 => ["name" => "FR TOURS& TRAVELS", "price" => 0],
            454 => ["name" => "ATIK OVERSEAS", "price" => 0],
            455 => ["name" => "DISCOVER CONSULTANTCY", "price" => 0],
            // Reference agencies for Patient Seeders
            995 => ["name" => "TAQWAH OVERSEAS", "price" => 3800],
            996 => ["name" => "RIDOY INTR", "price" => 3200],
            997 => ["name" => "RAIHAN VAI", "price" => 3500],
            998 => ["name" => "TAZ TOURS", "price" => 3500],
            999 => ["name" => "NM Tours & Travels", "price" => 3500],
        ];

        $agencies = [];
        foreach ($agenciesList as $id => $aData) {
            if (isset($agencies[$aData['name']])) {
                continue; // Skip duplicate names to prevent unique constraint violation
            }
            $agencies[$aData['name']] = Agency::create([
                'id' => $id,
                'name' => $aData['name'],
                'price' => $aData['price']
            ]);
        }

        // 4. Seed MRs
        $mrsList = [
            1 => ["name" => "MD SHELU RAHMAN", "role" => "MR"],
            2 => ["name" => "MST. HALIMA", "role" => "MR"],
            3 => ["name" => "KOWSHIQ", "role" => "MR"],
            4 => ["name" => "BEST OFFICE", "role" => "MR"],
            5 => ["name" => "SHAHIN", "role" => "MR"],
            6 => ["name" => "MD JAMAL", "role" => "MR"],
            7 => ["name" => "MD KAWSAR", "role" => "MR"],
            8 => ["name" => "SHIRIN SHELA", "role" => "MR"],
            9 => ["name" => "MONI AKTER", "role" => "MR"],
            10 => ["name" => "FYAZ", "role" => "MR"],
            11 => ["name" => "MD IMTIAZ", "role" => "MR"],
            12 => ["name" => "MD KAMRUL HASAN", "role" => "MR"],
            13 => ["name" => "SONIA", "role" => "MR"],
            14 => ["name" => "TUSHER", "role" => "MR"],
            15 => ["name" => "PREMA", "role" => "MR"],
            16 => ["name" => "AKHI", "role" => "MR"],
            17 => ["name" => "MUSTAFIZ", "role" => "MR"],
            18 => ["name" => "YASMIN", "role" => "MR"],
            19 => ["name" => "JINIA", "role" => "MR"],
            20 => ["name" => "ALDIN", "role" => "MR"],
            21 => ["name" => "DUNIYA", "role" => "MR"],
            22 => ["name" => "MARIA", "role" => "MR"],
            23 => ["name" => "BGO TRAVELS", "role" => "MR"],
            24 => ["name" => "SHELLY", "role" => "MR"],
            25 => ["name" => "MOSTAFIZ", "role" => "MR"],
            26 => ["name" => "SUMAIA", "role" => "MR"],
            27 => ["name" => "RUBEL", "role" => "MR"],
            28 => ["name" => "SULTAN AZAN", "role" => "MR"],
            29 => ["name" => "SHAWON", "role" => "MR"],
            30 => ["name" => "SOLEMAN", "role" => "MR"],
            31 => ["name" => "AZAN KUTUB", "role" => "MR"],
            // Reference MRs for Patient Seeders
            98 => ["name" => "MD TAHSIN ISLAM", "role" => "Senior MR"],
            99 => ["name" => "NABIUL HASAN", "role" => "MR"],
        ];

        $mrs = [];
        foreach ($mrsList as $id => $mData) {
            $mrs[$mData['name']] = Mr::create(array_merge($mData, ['id' => $id]));
        }

        // 5. Seed Patients
        $patientsData = [
            [
                'pax_id' => 'BEST000001',
                'first_name' => 'Rahim',
                'last_name' => 'Uddin',
                'father_name' => 'Abul Uddin',
                'mother_name' => 'Amena Begum',
                'mobile_no' => '8801700000001',
                'dob' => '1995-05-15',
                'sex' => 'Male',
                'passport_no' => 'BN0512983',
                'visa_no' => 'V123456',
                'issue_date' => '2026-01-01',
                'job_applied' => 'Labor',
                'country_name' => 'MALAYSIA',
                'agency_name' => 'SELF',
                'mr_name' => 'MD TAHSIN ISLAM',
                'medical_fee' => 3500,
                'received_amount' => 3500,
                'due_amount' => 0,
                'date' => '2026-07-04',
                'in_words' => 'Three Thousand Five Hundred Taka Only',
                'status' => 'Fit',
                'image_path' => 'patients/8XiZ5vhZ2IHexq17vaaRC1n7ev2UHHRhpb9ZySEz.jpg'
            ],
            [
                'pax_id' => 'BEST000002',
                'first_name' => 'Salma',
                'last_name' => 'Begum',
                'father_name' => 'Jalal Uddin',
                'mother_name' => 'Marium Begum',
                'mobile_no' => '8801700000002',
                'dob' => '1998-08-20',
                'sex' => 'Female',
                'passport_no' => 'BN0512871',
                'visa_no' => 'V789012',
                'issue_date' => '2026-02-15',
                'job_applied' => 'Housekeeper',
                'country_name' => 'U.A.E',
                'agency_name' => 'M/S SOHA OVERSEAS',
                'mr_name' => 'MD TAHSIN ISLAM',
                'medical_fee' => 3200,
                'received_amount' => 3000,
                'due_amount' => 200,
                'date' => '2026-07-04',
                'in_words' => 'Three Thousand Two Hundred Taka Only',
                'status' => 'Pending',
                'image_path' => 'patients/gfc4BVQs0hLGNUuxe1rnt0r3SILMHQSwZxT4OJCa.jpg'
            ],
            [
                'pax_id' => 'BEST000003',
                'first_name' => 'Karim',
                'last_name' => 'Ali',
                'father_name' => 'Kashem Ali',
                'mother_name' => 'Fatema Khatun',
                'mobile_no' => '8801700000003',
                'dob' => '1992-03-10',
                'sex' => 'Male',
                'passport_no' => 'BN0512790',
                'visa_no' => 'V345678',
                'issue_date' => '2026-03-01',
                'job_applied' => 'Technician',
                'country_name' => 'SINGAPORE',
                'agency_name' => 'TAQWAH OVERSEAS',
                'mr_name' => 'NABIUL HASAN',
                'medical_fee' => 3800,
                'received_amount' => 3800,
                'due_amount' => 0,
                'date' => '2026-07-03',
                'in_words' => 'Three Thousand Eight Hundred Taka Only',
                'status' => 'Fit',
                'image_path' => 'patients/SEmdjOMneCpGQ4KJEQXWS0yZUwo3ecbZKnLaZRIL.jpg'
            ],
            [
                'pax_id' => 'BEST000004',
                'first_name' => 'Nasir',
                'last_name' => 'Hossain',
                'father_name' => 'Idris Hossain',
                'mother_name' => 'Rasheda Begum',
                'mobile_no' => '8801700000004',
                'dob' => '1990-11-25',
                'sex' => 'Male',
                'passport_no' => 'BN0512612',
                'visa_no' => 'V901234',
                'issue_date' => '2026-04-10',
                'job_applied' => 'Construction',
                'country_name' => 'BAHRAIN',
                'agency_name' => 'MINHAZ OVERSEAS',
                'mr_name' => 'NABIUL HASAN',
                'medical_fee' => 3500,
                'received_amount' => 0,
                'due_amount' => 3500,
                'date' => '2026-07-03',
                'in_words' => 'Three Thousand Five Hundred Taka Only',
                'status' => 'Unfit',
                'image_path' => 'patients/UyFttx8MsohinyYyFDcYEgjK4WSp2EEOZPf1mHwr.jpg'
            ],
            [
                'pax_id' => 'BEST000005',
                'first_name' => 'Jamal',
                'last_name' => 'Uddin',
                'father_name' => 'Kamal Uddin',
                'mother_name' => 'Laila Begum',
                'mobile_no' => '8801700000005',
                'dob' => '1996-12-05',
                'sex' => 'Male',
                'passport_no' => 'BN0512534',
                'visa_no' => 'V567890',
                'issue_date' => '2026-05-20',
                'job_applied' => 'Driver',
                'country_name' => 'KUWAIT',
                'agency_name' => 'RIDOY INTR',
                'mr_name' => 'MD TAHSIN ISLAM',
                'medical_fee' => 3200,
                'received_amount' => 3200,
                'due_amount' => 0,
                'date' => '2026-07-02',
                'in_words' => 'Three Thousand Two Hundred Taka Only',
                'status' => 'Fit',
                'image_path' => 'patients/x09ZCaiz42pMP985NAcWTzTjtdDJ7cdK2cmMj0qN.jpg'
            ]
        ];

        foreach ($patientsData as $pData) {
            $patient = Patient::create([
                'pax_id' => $pData['pax_id'],
                'date' => $pData['date'],
                'country_id' => $countries[$pData['country_name']]->id,
                'first_name' => $pData['first_name'],
                'last_name' => $pData['last_name'],
                'father_name' => $pData['father_name'],
                'mother_name' => $pData['mother_name'],
                'mobile_no' => $pData['mobile_no'],
                'dob' => $pData['dob'],
                'sex' => $pData['sex'],
                'passport_no' => $pData['passport_no'],
                'visa_no' => $pData['visa_no'],
                'issue_date' => $pData['issue_date'],
                'job_applied' => $pData['job_applied'],
                'agency_id' => $agencies[$pData['agency_name']]->id,
                'mr_id' => $mrs[$pData['mr_name']]->id,
                'image_path' => $pData['image_path'] ?? null,
                'medical_fee' => $pData['medical_fee'],
                'received_amount' => $pData['received_amount'],
                'due_amount' => $pData['due_amount'],
                'in_words' => $pData['in_words'],
            ]);

            // Seed Medical Report for each patient
            MedicalReport::create([
                'patient_id' => $patient->id,
                'bld_group' => $pData['sex'] === 'Male' ? 'O+ve' : 'A+ve',
                'hiv_antibody' => 'Negative',
                'hbsag' => 'Negative',
                'hcv' => 'Negative',
                'malaria' => 'Negative',
                'tpha' => 'Negative',
                'tb' => 'Negative',
                'filariasis' => 'Negative',
                'leishmaniasis' => 'Negative',
                'leprosy' => 'Negative',
                'free_from_chronic' => 'Negative',
                'tumor_cancer' => 'Negative',
                'epilepsy' => 'Negative',
                'mental_illness' => 'Negative',
                'pregnancy' => 'Negative',
                'xray' => 'Negative',
                'physical' => 'Negative',
                'amp' => 'Nil',
                'albumin' => 'Nil',
                'medical_history' => 'No major illness.',
                'comments' => 'Fit for overseas work.',
                'final_status' => $pData['status'],
                'is_online' => 'Yes'
            ]);

            // Seed Xray Report for each patient
            XrayReport::create([
                'patient_id' => $patient->id,
                'date' => $pData['date'],
                'remark' => 'Normal chest radiograph findings.',
                'findings' => 'Lung fields are clear. Cardiac size is normal. Both domes of diaphragm are normal.',
                'result' => 'Normal'
            ]);
        }

        // 6. Seed Invoices (Transactions)
        AgencyInvoice::create([
            'invoice_no' => 'TR00001',
            'agency_id' => $agencies['SELF']->id,
            'date' => '2026-07-04',
            'user_id' => $admin->id,
            'net_amount' => 5000,
            'received_amount' => 5000,
            'due_amount' => 0,
            'in_words' => 'Five Thousand Taka Only',
            'payment_month' => '2026-07'
        ]);

        AgencyInvoice::create([
            'invoice_no' => 'TR00002',
            'agency_id' => $agencies['M/S SOHA OVERSEAS']->id,
            'date' => '2026-07-04',
            'user_id' => $admin->id,
            'net_amount' => 4200,
            'received_amount' => 3000,
            'due_amount' => 1200,
            'in_words' => 'Four Thousand Two Hundred Taka Only',
            'payment_month' => '2026-07'
        ]);

        AgencyInvoice::create([
            'invoice_no' => 'TR00003',
            'agency_id' => $agencies['TAQWAH OVERSEAS']->id,
            'date' => '2026-07-03',
            'user_id' => $admin->id,
            'net_amount' => 3800,
            'received_amount' => 0,
            'due_amount' => 3800,
            'in_words' => 'Three Thousand Eight Hundred Taka Only',
            'payment_month' => '2026-07'
        ]);
    }
}

