/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XrayRouteImport } from './routes/xray'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SearchPassportRouteImport } from './routes/search-passport'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportEntryRouteImport } from './routes/report-entry'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as MyEntriesRouteImport } from './routes/my-entries'
import { Route as MrListRouteImport } from './routes/mr-list'
import { Route as MedicalRouteImport } from './routes/medical'
import { Route as MalaysiaReportRouteImport } from './routes/malaysia-report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntryFormRouteImport } from './routes/entry-form'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as CountryListRouteImport } from './routes/country-list'
import { Route as AgencyListRouteImport } from './routes/agency-list'
import { Route as AgencyBalanceRouteImport } from './routes/agency-balance'
import { Route as AdminReportRouteImport } from './routes/admin-report'
import { Route as AccInfoRouteImport } from './routes/acc-info'
import { Route as IndexRouteImport } from './routes/index'

const XrayRoute = XrayRouteImport.update({
  id: '/xray',
  path: '/xray',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchPassportRoute = SearchPassportRouteImport.update({
  id: '/search-passport',
  path: '/search-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportEntryRoute = ReportEntryRouteImport.update({
  id: '/report-entry',
  path: '/report-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEntriesRoute = MyEntriesRouteImport.update({
  id: '/my-entries',
  path: '/my-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const MrListRoute = MrListRouteImport.update({
  id: '/mr-list',
  path: '/mr-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalRoute = MedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const MalaysiaReportRoute = MalaysiaReportRouteImport.update({
  id: '/malaysia-report',
  path: '/malaysia-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryFormRoute = EntryFormRouteImport.update({
  id: '/entry-form',
  path: '/entry-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryListRoute = CountryListRouteImport.update({
  id: '/country-list',
  path: '/country-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyListRoute = AgencyListRouteImport.update({
  id: '/agency-list',
  path: '/agency-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyBalanceRoute = AgencyBalanceRouteImport.update({
  id: '/agency-balance',
  path: '/agency-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/admin-report',
  path: '/admin-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AccInfoRoute = AccInfoRouteImport.update({
  id: '/acc-info',
  path: '/acc-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acc-info': typeof AccInfoRoute
  '/admin-report': typeof AdminReportRoute
  '/agency-balance': typeof AgencyBalanceRoute
  '/agency-list': typeof AgencyListRoute
  '/country-list': typeof CountryListRoute
  '/database': typeof DatabaseRoute
  '/entry-form': typeof EntryFormRoute
  '/login': typeof LoginRoute
  '/malaysia-report': typeof MalaysiaReportRoute
  '/medical': typeof MedicalRoute
  '/mr-list': typeof MrListRoute
  '/my-entries': typeof MyEntriesRoute
  '/password': typeof PasswordRoute
  '/report-entry': typeof ReportEntryRoute
  '/roles': typeof RolesRoute
  '/search-passport': typeof SearchPassportRoute
  '/users': typeof UsersRoute
  '/xray': typeof XrayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acc-info': typeof AccInfoRoute
  '/admin-report': typeof AdminReportRoute
  '/agency-balance': typeof AgencyBalanceRoute
  '/agency-list': typeof AgencyListRoute
  '/country-list': typeof CountryListRoute
  '/database': typeof DatabaseRoute
  '/entry-form': typeof EntryFormRoute
  '/login': typeof LoginRoute
  '/malaysia-report': typeof MalaysiaReportRoute
  '/medical': typeof MedicalRoute
  '/mr-list': typeof MrListRoute
  '/my-entries': typeof MyEntriesRoute
  '/password': typeof PasswordRoute
  '/report-entry': typeof ReportEntryRoute
  '/roles': typeof RolesRoute
  '/search-passport': typeof SearchPassportRoute
  '/users': typeof UsersRoute
  '/xray': typeof XrayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acc-info': typeof AccInfoRoute
  '/admin-report': typeof AdminReportRoute
  '/agency-balance': typeof AgencyBalanceRoute
  '/agency-list': typeof AgencyListRoute
  '/country-list': typeof CountryListRoute
  '/database': typeof DatabaseRoute
  '/entry-form': typeof EntryFormRoute
  '/login': typeof LoginRoute
  '/malaysia-report': typeof MalaysiaReportRoute
  '/medical': typeof MedicalRoute
  '/mr-list': typeof MrListRoute
  '/my-entries': typeof MyEntriesRoute
  '/password': typeof PasswordRoute
  '/report-entry': typeof ReportEntryRoute
  '/roles': typeof RolesRoute
  '/search-passport': typeof SearchPassportRoute
  '/users': typeof UsersRoute
  '/xray': typeof XrayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acc-info'
    | '/admin-report'
    | '/agency-balance'
    | '/agency-list'
    | '/country-list'
    | '/database'
    | '/entry-form'
    | '/login'
    | '/malaysia-report'
    | '/medical'
    | '/mr-list'
    | '/my-entries'
    | '/password'
    | '/report-entry'
    | '/roles'
    | '/search-passport'
    | '/users'
    | '/xray'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acc-info'
    | '/admin-report'
    | '/agency-balance'
    | '/agency-list'
    | '/country-list'
    | '/database'
    | '/entry-form'
    | '/login'
    | '/malaysia-report'
    | '/medical'
    | '/mr-list'
    | '/my-entries'
    | '/password'
    | '/report-entry'
    | '/roles'
    | '/search-passport'
    | '/users'
    | '/xray'
  id:
    | '__root__'
    | '/'
    | '/acc-info'
    | '/admin-report'
    | '/agency-balance'
    | '/agency-list'
    | '/country-list'
    | '/database'
    | '/entry-form'
    | '/login'
    | '/malaysia-report'
    | '/medical'
    | '/mr-list'
    | '/my-entries'
    | '/password'
    | '/report-entry'
    | '/roles'
    | '/search-passport'
    | '/users'
    | '/xray'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccInfoRoute: typeof AccInfoRoute
  AdminReportRoute: typeof AdminReportRoute
  AgencyBalanceRoute: typeof AgencyBalanceRoute
  AgencyListRoute: typeof AgencyListRoute
  CountryListRoute: typeof CountryListRoute
  DatabaseRoute: typeof DatabaseRoute
  EntryFormRoute: typeof EntryFormRoute
  LoginRoute: typeof LoginRoute
  MalaysiaReportRoute: typeof MalaysiaReportRoute
  MedicalRoute: typeof MedicalRoute
  MrListRoute: typeof MrListRoute
  MyEntriesRoute: typeof MyEntriesRoute
  PasswordRoute: typeof PasswordRoute
  ReportEntryRoute: typeof ReportEntryRoute
  RolesRoute: typeof RolesRoute
  SearchPassportRoute: typeof SearchPassportRoute
  UsersRoute: typeof UsersRoute
  XrayRoute: typeof XrayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xray': {
      id: '/xray'
      path: '/xray'
      fullPath: '/xray'
      preLoaderRoute: typeof XrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-passport': {
      id: '/search-passport'
      path: '/search-passport'
      fullPath: '/search-passport'
      preLoaderRoute: typeof SearchPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-entry': {
      id: '/report-entry'
      path: '/report-entry'
      fullPath: '/report-entry'
      preLoaderRoute: typeof ReportEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-entries': {
      id: '/my-entries'
      path: '/my-entries'
      fullPath: '/my-entries'
      preLoaderRoute: typeof MyEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mr-list': {
      id: '/mr-list'
      path: '/mr-list'
      fullPath: '/mr-list'
      preLoaderRoute: typeof MrListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical': {
      id: '/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof MedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malaysia-report': {
      id: '/malaysia-report'
      path: '/malaysia-report'
      fullPath: '/malaysia-report'
      preLoaderRoute: typeof MalaysiaReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry-form': {
      id: '/entry-form'
      path: '/entry-form'
      fullPath: '/entry-form'
      preLoaderRoute: typeof EntryFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country-list': {
      id: '/country-list'
      path: '/country-list'
      fullPath: '/country-list'
      preLoaderRoute: typeof CountryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-list': {
      id: '/agency-list'
      path: '/agency-list'
      fullPath: '/agency-list'
      preLoaderRoute: typeof AgencyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-balance': {
      id: '/agency-balance'
      path: '/agency-balance'
      fullPath: '/agency-balance'
      preLoaderRoute: typeof AgencyBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-report': {
      id: '/admin-report'
      path: '/admin-report'
      fullPath: '/admin-report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acc-info': {
      id: '/acc-info'
      path: '/acc-info'
      fullPath: '/acc-info'
      preLoaderRoute: typeof AccInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccInfoRoute: AccInfoRoute,
  AdminReportRoute: AdminReportRoute,
  AgencyBalanceRoute: AgencyBalanceRoute,
  AgencyListRoute: AgencyListRoute,
  CountryListRoute: CountryListRoute,
  DatabaseRoute: DatabaseRoute,
  EntryFormRoute: EntryFormRoute,
  LoginRoute: LoginRoute,
  MalaysiaReportRoute: MalaysiaReportRoute,
  MedicalRoute: MedicalRoute,
  MrListRoute: MrListRoute,
  MyEntriesRoute: MyEntriesRoute,
  PasswordRoute: PasswordRoute,
  ReportEntryRoute: ReportEntryRoute,
  RolesRoute: RolesRoute,
  SearchPassportRoute: SearchPassportRoute,
  UsersRoute: UsersRoute,
  XrayRoute: XrayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
